updated makefile and readme with new name for galasactl-darwin-amd64
galasa-dev/cli pull request #144
Opened 2023-09-01 12:12 UTC by Wyvinar

This is now galasactl-darwin-x86_64.

2023-09-01 12:15 UTC, techcobweb approved these changes

2023-09-01 12:32 UTC, galasa-team commented
Build successful

2023-09-01 13:14 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-144-wcjpr for details. If you are unable to do so, please contact a member of the Galasa team.

2023-09-01 14:14 UTC, jadecarino requested changes

2023-09-01 14:14 UTC, jadecarino commented on README.md
> +- Bleeding edge/Unstable : `docker pull harbor.galasa.dev/galasadev/galasa-cli-x86_64:main`
We are going to leave the Docker images with the same names for now so could you change this back please :)

2023-09-01 14:14 UTC, jadecarino commented on README.md
> +docker run harbor.galasa.dev/galasadev/galasa-cli-x86_64:main galasactl --version
Same as above

2023-09-01 14:20 UTC, jadecarino approved these changes

2023-09-01 14:35 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-144-rqtdd for details. If you are unable to do so, please contact a member of the Galasa team.

2023-09-04 09:17 UTC, techcobweb approved these changes

2023-09-04 09:23 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-144-vjp67 for details. If you are unable to do so, please contact a member of the Galasa team.

2023-09-04 09:43 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-144-bs29f for details. If you are unable to do so, please contact a member of the Galasa team.

2023-09-04 09:50 UTC, techcobweb commented
The docker-build phase of the tekton build process is failing.

```
INFO[0000] Retrieving image manifest alpine:3.17.1      
INFO[0000] Retrieving image alpine:3.17.1 from registry [index.docker.io](http://index.docker.io/) 
E0904 09:43:02.794102      16 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
INFO[0002] Built cross stage deps: map[]                
INFO[0002] Retrieving image manifest alpine:3.17.1      
INFO[0002] Returning cached image manifest              
INFO[0002] Executing 0 build triggers                   
INFO[0002] Unpacking rootfs as cmd RUN addgroup galasa &&     adduser -D -G galasa -h /galasa -s /bin/sh galasa requires it. 
INFO[0003] Taking snapshot of full filesystem...        
INFO[0004] ARG platform                                 
INFO[0004] RUN addgroup galasa &&     adduser -D -G galasa -h /galasa -s /bin/sh galasa 
INFO[0004] cmd: /bin/sh                                 
INFO[0004] args: [-c addgroup galasa &&     adduser -D -G galasa -h /galasa -s /bin/sh galasa] 
INFO[0004] Running: [/bin/sh -c addgroup galasa &&     adduser -D -G galasa -h /galasa -s /bin/sh galasa] 
error building image: error building stage: failed to get files used from context: failed to get fileinfo for /workspace/git/repo-cli-pr-144-bs29f/cli/bin/galasactl-linux-amd64: lstat /workspace/git/repo-cli-pr-144-bs29f/cli/bin/galasactl-linux-amd64: no such file or directory
```

2023-09-04 14:35 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-144-bs29f-r-57vds for details. If you are unable to do so, please contact a member of the Galasa team.

2023-09-04 15:42 UTC, galasa-team commented
Build successful

2023-09-04 15:51 UTC, merged