infix functionality for properties get
galasa-dev/cli pull request #156
Opened 2023-10-03 13:43 UTC by Akyiaa

2023-10-03 13:48 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-156-9jkmv for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-03 14:01 UTC, KirbyKatcher requested changes

2023-10-03 14:01 UTC, KirbyKatcher commented on pkg/properties/propertiesGet_test.go
These tests appear to be testing the API functionality not the CLI.
You should be able to delete them without impacting your testing coverage

2023-10-03 14:05 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-156-rklr4 for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-03 14:14 UTC, KirbyKatcher commented on pkg/cmd/propertiesGet.go
> +	propertiesGetCmd.PersistentFlags().StringVar(&propertiesInfix, "infix", "", "returns properties from a specified namespace which contains the supplied infix or at least one of the supplied infixes i
Can we change these to the
```
Prefix to match against the start of the property name within the namespace
Infix(es) that could be part of the property name within the namespace, multiples are supplied as comma-separated list
Suffix to match against the end of the property name within the namespace
```

2023-10-03 14:16 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-156-x2vlr for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-03 14:22 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-156-n5n7l for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-03 14:23 UTC, eamansour approved these changes
Looks good, just one suggestion - approved!

2023-10-03 14:23 UTC, eamansour commented on pkg/cmd/propertiesGet.go
> +	propertiesGetCmd.PersistentFlags().StringVar(&propertiesInfix, "infix", "", "Infix(es) that could be part of the property name within the namespace, multiples are supplied as comma-separated list")
Do you think something like "... multiple infixes can be supplied ..." would read better than "... multiples are supplied..."?

2023-10-03 14:34 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-156-cjs7v for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-04 10:43 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-156-hjlj5 for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-04 12:55 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-156-g5r4c for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-06 12:57 UTC, merged