`auth tokens delete` command
galasa-dev/cli pull request #244
Opened 2024-05-29 10:30 UTC by Akyiaa

## Why?
See story: https://github.com/galasa-dev/projectmanagement/issues/1729

## Changes
- Added `auth tokens delete` command to revoke personal access tokens given a token ID using the `--tokenid` flag

2024-05-29 10:47 UTC, galasa-team commented
Build successful

2024-05-30 15:12 UTC, galasa-team commented
Build successful

2024-05-30 15:59 UTC, galasa-team commented
Build successful

2024-05-31 09:21 UTC, galasa-team commented
Build successful

2024-05-31 09:32 UTC, galasa-team commented
Build successful

2024-05-31 15:16 UTC, eamansour requested changes
Looking good! Just a few bits to improve on :)

2024-05-31 15:16 UTC, eamansour commented on pkg/errors/errorMessage.go
> +	GALASA_ERROR_FAILED_TO_COMPILE_TOKEN_ID_REGEX = NewMessageType("GAL1155E: Unable to compile the regex pattern for the provided token id. Reason: '%s'", 1155, STACK_TRACE_NOT_WANTED)
I think this would also be a programming logic error since the user won't be able to do anything about it

2024-05-31 15:16 UTC, eamansour commented on pkg/errors/errorMessage.go
> +	GALASA_ERROR_INVALID_TOKEN_ID_FORMAT          = NewMessageType("GAL1156E: The provided token id, '%s', provided does not match formatting requirements. The token id must be an alphanumeric string on
Can't be certain the ID will always be alphanumeric!

2024-05-31 15:16 UTC, eamansour commented on docs/generated/galasactl_auth_tokens_delete.md
> +      --tokenId string   The ID of the token to be deleted. This is an alphanumeric string
Might not always be an alphanumeric string! (e.g. if an ID is `abcd-1234-xyz`, we should accept it)

2024-06-03 14:33 UTC, galasa-team commented
Build successful

2024-07-02 12:59 UTC, galasa-team commented
Build successful

2024-07-02 14:10 UTC, galasa-team commented
Build successful

2024-07-02 14:12 UTC, galasa-team commented
Build successful

2024-07-02 15:59 UTC, galasa-team commented
Build successful

2024-07-03 08:58 UTC, KirbyKatcher approved these changes

2024-07-03 13:37 UTC, merged