Added new users command to cli
galasa-dev/cli pull request #271
Opened 2024-08-16 14:52 UTC by aashir21

Signed-off-by: Aashir Siddiqui <aashir_sidiki@hotmail.com>

2024-08-16 15:13 UTC, galasa-team commented
Build successful

2024-08-19 16:04 UTC, galasa-team commented
Build successful

2024-08-19 16:08 UTC, galasa-team commented
Build successful

2024-08-20 08:55 UTC, techcobweb commented on pkg/users/users.go
> +	if err == nil {
Can we trim the string and use the trimmed content ? currently we trim it to check for blank, but throw it away.

2024-08-20 09:11 UTC, techcobweb commented on pkg/users/users.go
> +	if err == nil {
Probably have to return the modified loginId so the caller can use it.

2024-08-20 09:22 UTC, techcobweb commented on pkg/users/usersGet.go
> +			err = json.Unmarshal(outputText, &userData)
This can be avoided. See below.

2024-08-20 09:22 UTC, techcobweb commented on pkg/users/usersGet.go
> +				return userPropertiesJSON, err
I don't like multiple return statements in a function.
Why do we pass back JSON bytes ? We have the user properties, can't we return those ? Then we wouldn't need to turn it back from JSON to a structure again.

2024-08-20 09:24 UTC, techcobweb requested changes
Some changes requested. But looks good.

2024-08-20 10:39 UTC, galasa-team commented
Build successful

2024-08-22 09:29 UTC, techcobweb commented on pkg/users/users.go
> +	loginId = strings.TrimSpace(loginId)
Duplicate code of Trimspace with the above. Some moving around of the if logic will mean you only do that once.

2024-08-22 09:32 UTC, techcobweb commented on pkg/users/usersGet.go
> +		outputText, err = getUserDataFromRestApi(loginId, apiClient)
outputText is oddly named. It's not text which is returned. It's a user

2024-08-22 09:32 UTC, techcobweb commented on pkg/users/usersGet.go
> +func getUserDataFromRestApi(
As this method is called getUserData... I would expect it to return a single user data record, not an array.

2024-08-22 09:37 UTC, techcobweb approved these changes
Approved assuming the minor comments are sorted out.

2024-08-22 10:03 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-271-8rlrt for details. If you are unable to do so, please contact a member of the Galasa team.

2024-08-22 10:31 UTC, galasa-team commented
Build successful

2024-08-22 13:29 UTC, galasa-team commented
Build successful

2024-08-22 13:48 UTC, merged