look at ras/run/runid endpoint if not summary format
galasa-dev/cli pull request #91
Opened 2023-05-17 18:27 UTC by AaronJhaj

- URLs changed in CLI from /ras/run to /ras/runs
- CLI tries to validate the runid prior to sending it to the REST API on runs get
- Decides whether the fine-details are needed based on the formatter chosen... added to the formatter interface.
- Other minor updates.

2023-05-17 19:57 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-91-sbqgx for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-18 08:13 UTC, KirbyKatcher commented on pkg/runs/runsGet.go
> +				runJson, err = GetRunDetailsFromRasSearchRuns(runJson, apiServerUrl)
Shouldn't the input and output variable be a runArray as it is not in a json format at this point?

2023-05-18 08:17 UTC, KirbyKatcher requested changes
Can we add some more tests to check the new instructions for pulling the details view down. I can't see any for ras/run/{runid} in runsGet_test.go

2023-05-18 08:17 UTC, KirbyKatcher commented on pkg/runs/runsGet_test.go
> +		if strings.Contains(r.URL.Path, "/ras/run/") {
Do we have a test for /ras/run/{runid} as well?

2023-05-18 10:32 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-91-5zqm7 for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-18 10:56 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-91-5zqm7-r-8g7cc for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-18 15:54 UTC, KirbyKatcher approved these changes

2023-05-22 08:21 UTC, techcobweb commented on pkg/runs/runsGet.go
> +				err = galasaErrors.NewGalasaError(galasaErrors.GALASA_ERROR_QUERY_RUNS_FAILED, err.Error())
Might be nice to log the http status code, or even mention it in the error message ?

2023-05-22 08:25 UTC, techcobweb commented on pkg/runs/runsGet_test.go
>  		}
method getting too big. Seems that it could be split into one method which decides what to do, and 2 new methods which actually do things ?

2023-05-22 19:47 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-91-9t6ng for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-23 10:51 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-91-sb5xj for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-23 12:32 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-91-g6j6v for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-23 12:49 UTC, merged