1450-record-count-and-82-age-parameters
galasa-dev/cli pull request #97
Opened 2023-05-25 15:52 UTC by KirbyKatcher

2023-05-25 16:03 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-97-snfh6 for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-25 16:06 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-97-4qgrp for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-26 08:39 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-97-grs57 for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-26 08:53 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-97-zj4wh for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-26 09:04 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-cli-pr-97-jcdhq for details. If you are unable to do so, please contact a member of the Galasa team.

2023-05-26 09:18 UTC, galasa-team commented
Build successful

2023-05-30 10:20 UTC, galasa-team commented
Build successful

2023-05-30 11:01 UTC, techcobweb commented on docs/generated/errors-list.md
> +- GAL1076E: Badly formed from or to value '{}' specified in the age parameter. The value could not be converted into an integer value.
Put the 'from' and 'to' in quotes, as they are values we expect users to use...

2023-05-30 11:03 UTC, techcobweb commented on docs/generated/errors-list.md
> +- GAL1079E: Badly formed age parameter '{}' specified. Age of the tests should be specified in FROM:TO or FROM format with the units w (weeks), d (days) or h (hours).
add `where the FROM or TO parts of the value are integers, separated by a ':' separator.

2023-05-30 11:11 UTC, techcobweb commented on pkg/cmd/runsGet.go
> +	runsGetCmd.PersistentFlags().StringVar(&age, "age", "", "the age of the test run(s) we want information about. Supported formats are: --age FROM, --age FROM:TO. Supported units are days, weeks and h
Better wording: ?

Supported formats are: 'FROM' or 'FROM:TO', where FROM and TO are each ages, made up of an integer and a time-unit qualifier. Supported time-units are days, weeks and hours. Examples: --age 1d, --age 6h:1h")

are 'days' 'hours' also supported ?

2023-05-30 11:17 UTC, techcobweb commented on pkg/errors/errorMessage.go
> +	GALASA_ERROR_NO_RUNNAME_OR_AGE_SPECIFIED    = NewMessageType("GAL1080E: Neither a runname or an age have been specified. Either specify a runname or an age of the tests you want to see.", 1080, STAC
Neither ... nor is harder to read than Either ... or - best to avoid it if possible.

2023-05-30 11:23 UTC, techcobweb commented on pkg/runs/runsGet.go
> +	var toAge int
You need to split based on presence of a colon first ?

2023-05-30 11:24 UTC, techcobweb commented on pkg/runs/runsGet.go
> +	if len(submatches) != 0 {
I could add a value "15d45dAndaloadofcraphere" and it would still be valid.

2023-05-30 11:25 UTC, techcobweb commented on pkg/runs/runsGet.go
> +func getTimesFromAge(age string) (int, int, error) {
Don't see any unit tests for this bit ? would be easier to unit test it in isolation.

2023-05-30 11:30 UTC, techcobweb commented on pkg/runs/runsGet_test.go
>  	// Given ...
Other tests: 
- Miss out the colon - should fail
- 2d:2w should fail, to time is bigger
- garbage
- :garbage
- :2w

2023-05-30 11:34 UTC, techcobweb requested changes
Think the age parsing and tests need improvement.

2023-05-30 11:35 UTC, techcobweb commented on pkg/runs/runsGet_test.go
>  	// Given ...
Also, you can test the detailed method, rather than with the whole request response stuff.

Not really testing much different each time otherwise.

2023-05-30 15:35 UTC, galasa-team commented
Build successful

2023-05-30 18:59 UTC, techcobweb commented on pkg/runs/runsGet_test.go
>  	// Given ...
We coded these test up together.

2023-05-30 19:00 UTC, techcobweb commented on pkg/runs/runsGet.go
> +	var toAge int
Done

2023-05-30 19:01 UTC, merged